#!/usr/bin/env zsh

# Clean it up
rm -drf ./dist

# Build it
npm run build

# Switch to gh-pages branch
git checkout gh-pages

# Move everything from ./dist to the root
rsync \
  --delete-after \
  --recursive \
  --exclude=dist \
  --exclude=node_modules \
  --exclude=.git \
  --exclude=.gitignore \
  ./dist/ \
  .

# Commit
git add .
git commit -a -m "Building for gh-pages"

# Pushing
git push origin gh-pages

# Get back to master
git checkout master
