#!/usr/bin/env bash
set -e

rm -rf ./dist
mkdir -p ./dist

cp \
  ./app/./css/* \
  ./app/./img/* \
  ./app/./js/*.js \
  ./app/./*.html \
  ./app/./*.json \
  ./dist

jsx --extension jsx ./app/js/ ./dist/js/
